# Generated by Django 2.1.7 on 2019-07-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0002_author_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
