# Generated by Django 2.1.7 on 2019-07-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0003_payment_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
