# Generated by Django 2.1.7 on 2019-07-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0004_article_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalitem',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
    ]
