# Generated by Django 2.1.7 on 2019-07-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0005_additionalitem_can_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
