# Generated by Django 2.1.7 on 2019-07-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0007_auto_20190729_0333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentitem',
            old_name='discount',
            new_name='price_us',
        ),
        migrations.RemoveField(
            model_name='paymentitem',
            name='currency',
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
