# Generated by Django 2.1.7 on 2019-07-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0009_auto_20190729_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='THB', max_length=3),
        ),
    ]
