# Generated by Django 2.1.7 on 2019-09-08 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import regist.models


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0010_payment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ieee',
            field=models.ImageField(blank=True, null=True, upload_to=regist.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='slip',
            field=models.ImageField(blank=True, null=True, upload_to=regist.models.path_and_rename),
        ),
    ]
