# Generated by Django 2.1.7 on 2019-09-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0013_auto_20190909_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalitem',
            old_name='early_price',
            new_name='early_disc',
        ),
        migrations.RenameField(
            model_name='additionalitem',
            old_name='early_price_us',
            new_name='early_disc_us',
        ),
    ]
