# Generated by Django 2.1.7 on 2019-09-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0017_auto_20190912_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_jcsi',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_ugm',
        ),
        migrations.AddField(
            model_name='author',
            name='is_jcsi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='is_ugm',
            field=models.BooleanField(default=False),
        ),
    ]
